# Generated by Django 3.2 on 2022-11-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asosciado',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('num_cuenta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Producto',
            fields=[
                ('cod_catgoria', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('domicilio', models.CharField(max_length=100)),
                ('num_cuenta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Orden',
            fields=[
                ('cod_orden', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion Orden')),
                ('sub_total', models.FloatField()),
                ('iva', models.PositiveSmallIntegerField()),
                ('total', models.FloatField()),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_cliente', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_Pago',
            fields=[
                ('cod_metodo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Porcentajes',
            fields=[
                ('id_procentaje', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=255)),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Tipo_Documento',
            fields=[
                ('cod_tipo_documento', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('abreviacion', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Tipo_Persona',
            fields=[
                ('cod_tipo_persona', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('abreviacion', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='productos/%d/%m/%Y/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion Producto')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha Edicion Producto')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.categoria_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('cod_pago', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dni_cliente', models.IntegerField()),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion Pago')),
                ('id_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_metodo', to='core.metodos_pago')),
                ('id_orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.detalle_orden')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_cliente', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('estado_envio', models.CharField(max_length=20)),
                ('id_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Inversiones',
            fields=[
                ('cod_inversion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_inversion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion Inversion')),
                ('estado', models.CharField(max_length=20)),
                ('dni_asociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.asosciado')),
                ('dni_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.orden_compra')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_Ganancias',
            fields=[
                ('cod_ganancias', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_ganancia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion Ganancia')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_update', models.DateTimeField(auto_now=True, verbose_name='Decha Edicion Ganancia')),
                ('dni_asociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.asosciado')),
                ('dni_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_inversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.historial_inversiones')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_orden',
            name='id_producto',
            field=models.ManyToManyField(related_name='do_producto', to='core.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli_documento', to='core.ref_tipo_documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli_persona', to='core.ref_tipo_persona'),
        ),
        migrations.AddField(
            model_name='asosciado',
            name='id_tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aso_documento', to='core.ref_tipo_documento'),
        ),
        migrations.AddField(
            model_name='asosciado',
            name='id_tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aso_persona', to='core.ref_tipo_persona'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=10)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('id_tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_documento', to='core.ref_tipo_documento')),
                ('id_tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_persona', to='core.ref_tipo_persona')),
            ],
        ),
    ]
