# Generated by Django 3.2 on 2022-11-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_ganancias',
            name='fecha_update',
        ),
    ]
