# Generated by Django 3.2 on 2022-11-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_historia_ganancias_fecha_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodos_pago',
            options={'verbose_name': 'Metodo Pago'},
        ),
    ]
