# Generated by Django 3.2 on 2022-11-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_metodos_pago_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('cod_mensaje', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dni_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('apellido_cliente', models.CharField(max_length=30)),
                ('email_receptor', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=800)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion Mensaje')),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'Administrador'},
        ),
        migrations.AlterModelOptions(
            name='categoria_producto',
            options={'verbose_name_plural': 'Categoria De Productos'},
        ),
        migrations.AlterModelOptions(
            name='detalle_orden',
            options={'verbose_name_plural': 'Detalles De Orden'},
        ),
        migrations.AlterModelOptions(
            name='historia_ganancias',
            options={'verbose_name_plural': 'Historial De Ganancias'},
        ),
        migrations.AlterModelOptions(
            name='historial_inversiones',
            options={'verbose_name_plural': 'Historial De Inversiones'},
        ),
        migrations.AlterModelOptions(
            name='metodos_pago',
            options={'verbose_name_plural': 'Metodos De Pago'},
        ),
        migrations.AlterModelOptions(
            name='orden_compra',
            options={'verbose_name_plural': 'Ordenes De Compra'},
        ),
        migrations.AlterModelOptions(
            name='porcentajes',
            options={'verbose_name_plural': 'Porcentajes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['cod_producto']},
        ),
        migrations.AlterModelOptions(
            name='ref_tipo_documento',
            options={'verbose_name_plural': 'Tipo De Documentos'},
        ),
        migrations.AlterModelOptions(
            name='ref_tipo_persona',
            options={'verbose_name_plural': 'Tipo De Personas'},
        ),
    ]
