# Generated by Django 3.2 on 2024-11-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221123_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email_receptor',
            new_name='email_remitente',
        ),
    ]
