# Generated by Django 3.2 on 2024-11-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_email_receptor_contacto_email_remitente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='dni_cliente',
        ),
    ]
