# Generated by Django 3.2 on 2024-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contacto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha Creacion Mensaje'),
        ),
    ]
