# Generated by Django 3.2 on 2025-01-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250124_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_persona', to='core.ref_tipo_persona'),
        ),
    ]
