# Generated by Django 3.2 on 2025-01-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_id_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Ganancias',
            fields=[
                ('cod_ganancias', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_ganancia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ganancia')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado Ganancia')),
                ('valor_ganancia', models.FloatField(verbose_name='Valor Ganancia')),
            ],
            options={
                'verbose_name_plural': 'Historial De Ganancias',
            },
        ),
        migrations.AddField(
            model_name='historial_inversiones',
            name='valor_inversion',
            field=models.FloatField(default=0, verbose_name='Valor Inversión'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_documento', to='core.ref_tipo_documento', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_persona', to='core.ref_tipo_persona', verbose_name='Tipo Persona'),
        ),
        migrations.AlterField(
            model_name='asosciado',
            name='id_tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aso_documento', to='core.ref_tipo_documento', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='asosciado',
            name='id_tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aso_persona', to='core.ref_tipo_persona', verbose_name='Tipo Persona'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli_documento', to='core.ref_tipo_documento', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cli_persona', to='core.ref_tipo_persona', verbose_name='Tipo Persona'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='dni_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='fecha_orden',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='id_producto',
            field=models.ManyToManyField(related_name='do_producto', to='core.Producto', verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='historial_inversiones',
            name='dni_asociado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hi_asociado', to='core.asosciado', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='historial_inversiones',
            name='dni_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hi_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historial_inversiones',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado Inversión'),
        ),
        migrations.AlterField(
            model_name='historial_inversiones',
            name='fecha_inversion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inversión'),
        ),
        migrations.AlterField(
            model_name='historial_inversiones',
            name='id_orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hi_orden', to='core.orden_compra', verbose_name='Orden Compra'),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='dni_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado Compra'),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='estado_envio',
            field=models.CharField(max_length=20, verbose_name='Estado Envio'),
        ),
        migrations.AlterField(
            model_name='orden_compra',
            name='id_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oc_pago', to='core.pago', verbose_name='Codigo Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='dni_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_metodo', to='core.metodos_pago', verbose_name='Metodo Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.detalle_orden', verbose_name='Detalle Orden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.categoria_producto', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Historia_Ganancias',
        ),
        migrations.AddField(
            model_name='historial_ganancias',
            name='dni_asociado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hg_asociado', to='core.asosciado', verbose_name='Asociado'),
        ),
        migrations.AddField(
            model_name='historial_ganancias',
            name='dni_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hg_cliente', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historial_ganancias',
            name='id_inversion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hg_inversion', to='core.historial_inversiones', verbose_name='Inversion'),
        ),
    ]
